export { localDb } from './local-db'
export { syncOutbox } from './sync-outbox'
export { syncApi } from './sync-api'
export type { PushResult, PullResult, ContentManifest } from './sync-api'
export { assetCacheService } from './asset-cache.service'
export { learningPackService } from './learning-pack.service'
export { learningRepository } from './learning.repository'
export { learningContentRepository } from './learning-content.repository'
export { practiceRepository } from './practice.repository'
export { offlineSyncService } from './offline-sync.service'
export { offlineStorageService } from './offline-storage.service'
export { sqliteStorage } from './sqlite/sqlite-storage'
export { DB_NAME as SQLITE_DB_NAME, DB_VERSION as SQLITE_DB_VERSION, TABLE_NAMES as SQLITE_TABLE_NAMES } from './sqlite/schema'
export type { TableName as SqliteTableName } from './sqlite/schema'
export type { AssetRef, LocalAsset } from './asset-cache.service'
export type { LearningPackManifest, InstalledLearningPack } from './learning-pack.service'
export type { ExpressionEntry, ExpressionEntryKind, ExpressionEntryStatus, WordEntry, ChunkEntry, PatternEntry } from './learning-content.repository'
export type { SyncOutboxItem, SyncEntityType, SyncOperation } from './sync-outbox'
export type { OfflineStorageStats } from './offline-storage.service'
