"""Oxford 3000 Vocabulary Distributor for Foundation Packages.
Reads Oxford 3000 word list, distributes by CEFR level and theme to 10 packages."""

import csv
import json
import os
import re

PKG_DIR = r"C:\Users\z1309\Desktop\work\speakGuild\apps\backend\prisma\data\packages"
OXFORD_FILE = (
    r"C:\Users\z1309\Desktop\work\speakGuild\apps\backend\prisma\scripts\oxford_raw.txt"
)
FIELDS = [
    "scene_title",
    "topic_title",
    "word",
    "meaning",
    "part_of_speech",
    "phonetic_us",
    "phonetic_uk",
    "difficulty",
    "description",
    "examples_json",
    "sort_order",
]

# 1. Parse Oxford 3000
# Format per line: "word part_of_speech CEFR" or "word part_of_speech | CEFR, n. CEFR"
raw = open(OXFORD_FILE, encoding="utf-8").read()

entries = []  # (word, pos, cefr)
for line in raw.split("\n"):
    line = line.strip()
    # Skip header/footer lines
    if not line or line.startswith("©") or line.startswith("The Oxford"):
        continue
    # Parse: "abandon v. B2" or "ability n. A2" or "about prep., adv. A1"
    # Pattern: word [pos] CEFR
    m = re.match(r"^([a-z\s\-()\']+?)\s+((?:[a-z]+\.,?\s*)+)\s+([A-B]\d)", line)
    if m:
        word = m.group(1).strip()
        pos_raw = m.group(2).strip()
        cefr = m.group(3).strip()
        # Extract first POS
        pos = pos_raw.split(".")[0].split(",")[0].strip()
        if word and pos and cefr:
            entries.append((word, pos, cefr))

print(f"Parsed {len(entries)} Oxford 3000 entries")

# Stats by CEFR
from collections import Counter

cefr_counts = Counter(e[2] for e in entries)
print(f"By CEFR: {dict(cefr_counts)}")

# Get unique words
all_oxford_words = set(e[0].lower() for e in entries)
print(f"Unique words: {len(all_oxford_words)}")

# 2. Build word -> packages/themes mapping
# For each word, determine which package(s) it belongs to based on theme
# We use keyword matching against scene titles

# Theme keywords per package
PKG_THEMES = {
    1: {  # 英语入门 - A1 basic
        "intro": [
            "name",
            "hello",
            "goodbye",
            "friend",
            "teacher",
            "student",
            "meet",
            "nice",
            "please",
            "thank",
            "sorry",
            "excuse",
            "how",
            "old",
            "year",
            "what",
            "where",
            "who",
            "yes",
            "no",
            "not",
            "am",
            "is",
            "are",
            "be",
            "i",
            "you",
            "he",
            "she",
            "it",
            "we",
            "they",
            "my",
            "your",
            "his",
            "her",
            "our",
            "their",
        ],
        "describe": [
            "this",
            "that",
            "these",
            "those",
            "a",
            "an",
            "the",
            "big",
            "small",
            "long",
            "short",
            "tall",
            "new",
            "good",
            "bad",
            "beautiful",
            "ugly",
            "color",
            "red",
            "blue",
            "green",
            "yellow",
            "black",
            "white",
            "big",
            "small",
            "high",
            "low",
            "right",
            "wrong",
            "easy",
            "difficult",
            "same",
            "different",
            "on",
            "in",
            "under",
            "near",
            "here",
            "there",
            "book",
            "pen",
            "table",
            "chair",
            "door",
            "window",
            "bag",
            "box",
            "key",
            "weather",
            "sun",
            "rain",
            "snow",
            "wind",
            "cloud",
            "sunny",
            "rainy",
            "cloudy",
        ],
        "family": [
            "father",
            "mother",
            "brother",
            "sister",
            "son",
            "daughter",
            "family",
            "man",
            "woman",
            "child",
            "boy",
            "girl",
            "doctor",
            "nurse",
            "live",
            "love",
            "speak",
            "young",
            "happy",
            "sad",
            "kind",
        ],
        "greeting": [
            "morning",
            "afternoon",
            "evening",
            "night",
            "today",
            "tomorrow",
            "yesterday",
            "now",
            "soon",
            "later",
            "again",
            "then",
            "help",
            "see",
            "call",
            "introduce",
            "welcome",
            "question",
            "answer",
            "idea",
            "always",
            "never",
            "sometimes",
            "usually",
            "often",
        ],
        "number": [
            "one",
            "two",
            "three",
            "four",
            "five",
            "six",
            "seven",
            "eight",
            "nine",
            "ten",
            "eleven",
            "twelve",
            "twenty",
            "thirty",
            "forty",
            "fifty",
            "hundred",
            "thousand",
            "million",
            "first",
            "second",
            "third",
            "time",
            "half",
            "quarter",
            "minute",
            "hour",
            "day",
            "week",
            "month",
            "year",
            "monday",
            "tuesday",
            "wednesday",
            "thursday",
            "friday",
            "saturday",
            "sunday",
            "january",
            "february",
            "march",
            "april",
            "may",
            "june",
            "july",
            "august",
            "september",
            "october",
            "november",
            "december",
            "spring",
            "summer",
            "autumn",
            "winter",
            "birthday",
            "date",
            "number",
            "car",
            "bus",
            "bike",
            "taxi",
            "train",
            "plane",
            "street",
            "road",
            "city",
            "town",
            "country",
            "school",
            "home",
            "shop",
            "store",
            "restaurant",
            "hospital",
            "park",
            "bank",
            "hotel",
            "office",
            "station",
        ],
        "needs": [
            "want",
            "need",
            "like",
            "love",
            "can",
            "have",
            "eat",
            "drink",
            "sleep",
            "water",
            "food",
            "breakfast",
            "lunch",
            "dinner",
            "apple",
            "banana",
            "orange",
            "rice",
            "bread",
            "milk",
            "tea",
            "coffee",
            "sugar",
            "salt",
            "egg",
            "meat",
            "fish",
            "hungry",
            "thirsty",
            "tired",
            "hot",
            "cold",
            "warm",
            "head",
            "hand",
            "eye",
            "ear",
            "mouth",
            "nose",
            "hair",
            "arm",
            "leg",
            "foot",
            "body",
            "ill",
            "money",
            "price",
            "buy",
            "pay",
            "help",
            "make",
            "get",
            "use",
            "put",
            "find",
            "read",
            "write",
            "play",
            "walk",
            "run",
            "sit",
            "stand",
            "cook",
            "clean",
            "wash",
            "open",
            "close",
            "turn",
            "learn",
            "study",
            "teach",
            "listen",
            "hear",
            "watch",
            "look",
            "give",
            "show",
            "let",
            "bring",
            "try",
            "keep",
            "start",
            "stop",
            "talk",
            "work",
            "music",
            "song",
            "game",
            "sport",
            "ball",
            "movie",
        ],
    },
    # Theme word lists for packages 2-10 - checking if word matches ANY scene theme in the package
    2: [
        "routine",
        "habit",
        "daily",
        "get",
        "up",
        "wake",
        "shower",
        "wash",
        "brush",
        "dress",
        "leave",
        "arrive",
        "exercise",
        "break",
        "homework",
        "housework",
        "early",
        "late",
        "meal",
        "breakfast",
        "lunch",
        "dinner",
        "snack",
        "cook",
        "kitchen",
        "eat",
        "drink",
        "like",
        "enjoy",
        "prefer",
        "hate",
        "want",
        "need",
        "choose",
        "decision",
        "schedule",
        "plan",
        "appointment",
        "meeting",
        "class",
        "lesson",
        "drive",
        "ride",
        "take",
        "bus",
        "bike",
        "car",
        "train",
        "walk",
        "shop",
        "store",
        "buy",
        "pay",
        "price",
        "cost",
        "cheap",
        "expensive",
        "size",
        "wear",
        "try",
        "weather",
        "park",
        "beach",
        "zoo",
        "restaurant",
        "menu",
        "order",
        "dish",
        "delicious",
        "taste",
        "bill",
        "tip",
        "waiter",
        "soup",
        "salad",
        "juice",
        "call",
        "message",
        "email",
        "invite",
        "meet",
        "traffic",
        "apologize",
        "open",
        "close",
        "turn",
        "forget",
        "remember",
        "hurry",
        "bring",
        "together",
        "please",
        "polite",
        "patient",
        "quiet",
        "careful",
        "let",
        "go",
        "come",
        "sit",
        "stand",
    ],
    3: [
        "family",
        "father",
        "mother",
        "brother",
        "sister",
        "son",
        "daughter",
        "uncle",
        "aunt",
        "cousin",
        "nephew",
        "niece",
        "grandfather",
        "grandmother",
        "husband",
        "wife",
        "neighbor",
        "relative",
        "colleague",
        "classmate",
        "friend",
        "job",
        "singer",
        "dancer",
        "artist",
        "writer",
        "pilot",
        "farmer",
        "soldier",
        "police",
        "lawyer",
        "engineer",
        "manager",
        "reporter",
        "scientist",
        "cook",
        "dentist",
        "actor",
        "musician",
        "story",
        "tale",
        "describe",
        "explain",
        "brave",
        "clever",
        "honest",
        "polite",
        "patient",
        "shy",
        "funny",
        "smile",
        "laugh",
        "cry",
        "shout",
        "suddenly",
        "immediately",
        "begin",
        "appear",
        "seem",
        "everyone",
        "someone",
        "nobody",
        "everything",
        "something",
        "nothing",
        "both",
        "neither",
        "either",
        "their",
        "they",
        "than",
        "same",
        "different",
        "too",
        "also",
        "but",
    ],
    4: [
        "where",
        "how",
        "which",
        "what",
        "excuse",
        "pardon",
        "direction",
        "corner",
        "block",
        "opposite",
        "nearby",
        "crossing",
        "far",
        "near",
        "kilometer",
        "airport",
        "station",
        "platform",
        "ticket",
        "passenger",
        "luggage",
        "depart",
        "miss",
        "catch",
        "delay",
        "cancel",
        "price",
        "cost",
        "cheap",
        "expensive",
        "size",
        "try",
        "wear",
        "pay",
        "cash",
        "card",
        "receipt",
        "refund",
        "exchange",
        "discount",
        "menu",
        "dish",
        "order",
        "recommend",
        "serve",
        "waiter",
        "bill",
        "tip",
        "delicious",
        "taste",
        "service",
        "hobby",
        "interest",
        "meet",
        "invite",
        "join",
        "free",
        "busy",
        "available",
        "fun",
        "travel",
        "visit",
        "party",
        "weekend",
        "tonight",
        "speak",
        "message",
        "call",
        "contact",
        "number",
        "email",
        "wrong",
        "correct",
        "hear",
        "signal",
        "repeat",
        "slowly",
        "loudly",
        "urgent",
        "help",
        "emergency",
        "ambulance",
        "hospital",
        "pharmacy",
        "medicine",
        "police",
        "fire",
        "accident",
        "hurt",
        "pain",
        "fever",
        "sick",
        "injured",
        "lost",
        "thief",
        "steal",
        "dangerous",
        "safe",
        "language",
        "translate",
    ],
    5: [
        "action",
        "activity",
        "event",
        "happen",
        "occur",
        "currently",
        "recently",
        "now",
        "moment",
        "look",
        "watch",
        "listen",
        "notice",
        "observe",
        "change",
        "become",
        "grow",
        "improve",
        "increase",
        "reduce",
        "develop",
        "temporary",
        "permanent",
        "compare",
        "contrast",
        "usually",
        "normally",
        "generally",
        "often",
        "sometimes",
        "occasionally",
        "rarely",
        "seldom",
        "hardly",
        "never",
        "frequently",
        "regularly",
        "possession",
        "belong",
        "contain",
        "include",
        "receive",
        "obtain",
        "gain",
        "offer",
        "prefer",
        "get",
        "have",
    ],
    6: [
        "ago",
        "yesterday",
        "last",
        "before",
        "past",
        "memory",
        "remember",
        "forget",
        "remind",
        "experience",
        "adventure",
        "journey",
        "trip",
        "travel",
        "visit",
        "move",
        "graduate",
        "college",
        "university",
        "childhood",
        "teenager",
        "adult",
        "age",
        "then",
        "originally",
        "previously",
        "once",
        "ever",
        "never",
        "already",
        "yet",
        "just",
        "since",
        "for",
        "during",
        "was",
        "were",
        "had",
        "did",
        "went",
        "saw",
        "ate",
        "said",
        "made",
        "took",
        "came",
        "gave",
        "told",
        "knew",
        "thought",
        "bought",
        "taught",
        "felt",
        "sat",
        "ran",
        "wrote",
        "read",
        "built",
        "sent",
        "spoke",
        "stood",
        "slept",
        "achieve",
        "accomplish",
        "fail",
        "succeed",
        "attempt",
        "regret",
        "celebrate",
        "birthday",
        "wedding",
        "festival",
        "holiday",
    ],
    7: [
        "future",
        "tomorrow",
        "tonight",
        "predict",
        "expect",
        "hope",
        "possible",
        "probably",
        "maybe",
        "plan",
        "prepare",
        "goal",
        "aim",
        "promise",
        "swear",
        "guarantee",
        "offer",
        "willing",
        "refuse",
        "agree",
        "accept",
        "allow",
        "rule",
        "duty",
        "choice",
        "option",
        "decision",
        "decide",
        "choose",
        "select",
        "wish",
        "luck",
        "lucky",
        "congratulations",
        "success",
        "achieve",
        "polite",
        "manner",
        "respect",
        "grateful",
        "appreciate",
        "request",
        "permission",
        "suggestion",
        "recommend",
        "advise",
        "encourage",
        "support",
        "protect",
        "will",
        "shall",
        "may",
        "might",
        "must",
        "should",
        "could",
        "would",
        "need",
        "have",
        "going",
    ],
    8: [
        "however",
        "although",
        "though",
        "therefore",
        "thus",
        "hence",
        "furthermore",
        "moreover",
        "besides",
        "meanwhile",
        "otherwise",
        "instead",
        "unless",
        "whether",
        "whereas",
        "whenever",
        "wherever",
        "first",
        "second",
        "third",
        "next",
        "finally",
        "lastly",
        "since",
        "until",
        "while",
        "once",
        "immediately",
        "suddenly",
        "example",
        "instance",
        "including",
        "except",
        "actually",
        "basically",
        "generally",
        "especially",
        "particularly",
        "mainly",
        "plus",
        "together",
        "because",
        "cause",
        "reason",
        "result",
        "effect",
        "purpose",
        "order",
        "sequence",
        "step",
        "additional",
        "extra",
        "but",
        "and",
        "or",
        "so",
        "if",
    ],
    9: [
        "than",
        "as",
        "more",
        "less",
        "most",
        "least",
        "better",
        "worse",
        "best",
        "worst",
        "bigger",
        "smaller",
        "faster",
        "slower",
        "cheaper",
        "older",
        "younger",
        "similar",
        "same",
        "different",
        "alike",
        "unlike",
        "opposite",
        "between",
        "among",
        "through",
        "across",
        "along",
        "around",
        "behind",
        "front",
        "beside",
        "next",
        "above",
        "below",
        "inside",
        "outside",
        "position",
        "location",
        "corner",
        "center",
        "middle",
        "edge",
        "surface",
        "top",
        "bottom",
        "side",
        "quality",
        "standard",
        "level",
        "popular",
        "famous",
        "favorite",
        "excellent",
        "perfect",
        "terrible",
        "quickly",
        "slowly",
        "carefully",
        "well",
        "badly",
        "hard",
        "fast",
        "prefer",
        "recommend",
        "suggest",
        "advise",
        "choose",
        "decide",
    ],
    10: [
        "think",
        "believe",
        "suppose",
        "imagine",
        "consider",
        "know",
        "understand",
        "realize",
        "recognize",
        "wonder",
        "doubt",
        "guess",
        "conclude",
        "admit",
        "deny",
        "suggest",
        "mention",
        "explain",
        "agree",
        "hope",
        "which",
        "who",
        "that",
        "whose",
        "where",
        "when",
        "describe",
        "person",
        "place",
        "reason",
        "time",
        "thing",
        "kind",
        "type",
        "someone",
        "something",
        "everyone",
        "everything",
        "want",
        "hope",
        "plan",
        "decide",
        "need",
        "choose",
        "promise",
        "try",
        "forget",
        "remember",
        "would",
        "purpose",
        "aim",
        "goal",
        "important",
        "necessary",
        "essential",
        "useful",
        "helpful",
        "difficult",
        "easy",
        "possible",
        "hard",
        "enjoy",
        "like",
        "love",
        "hate",
        "prefer",
        "finish",
        "keep",
        "continue",
        "start",
        "begin",
        "stop",
        "avoid",
        "practice",
        "consider",
        "suggest",
        "imagine",
        "risk",
        "admit",
        "deny",
    ],
}

# 3. Read all scene titles
all_scenes = {}
for pkg_num in range(1, 11):
    pkg_name = f"foundation-{pkg_num}"
    dir_map = {
        1: "foundation-1-beginner",
        2: "foundation-2-daily-life",
        3: "foundation-3-daily-work",
        4: "foundation-4-essential-phrases",
        5: "foundation-5-opinion-basics",
        6: "foundation-6-social-express",
        7: "foundation-7-travel-basic",
        8: "foundation-8-integrated-express",
        9: "foundation-9-describe-compare",
        10: "foundation-10-clause-gerund-infinitive",
    }
    pkg_dir = os.path.join(PKG_DIR, dir_map[pkg_num])
    scenes = []
    with open(os.path.join(pkg_dir, "scenes.csv"), encoding="utf-8") as f:
        for r in csv.DictReader(f):
            scenes.append(r["title"])
    all_scenes[pkg_num] = scenes

# 4. For PK①: assign A1 words to scenes by theme
PKG1_SCENE_THEMES = {
    0: [
        "intro",
        "name",
        "hello",
        "goodbye",
        "friend",
        "teacher",
        "student",
        "meet",
        "nice",
        "please",
        "thank",
        "sorry",
        "how",
        "old",
        "year",
        "what",
        "where",
        "who",
        "yes",
        "no",
        "be",
        "am",
        "is",
        "are",
        "i",
        "you",
        "he",
        "she",
        "it",
        "we",
        "they",
        "my",
        "your",
        "his",
        "her",
        "our",
        "their",
        "me",
        "him",
        "us",
        "them",
        "too",
        "very",
        "also",
        "sure",
        "well",
        "great",
        "fine",
        "okay",
        "excuse",
        "call",
        "know",
        "think",
        "do",
        "say",
        "tell",
        "ask",
        "go",
        "come",
    ],
    1: [
        "this",
        "that",
        "these",
        "those",
        "a",
        "an",
        "the",
        "some",
        "any",
        "all",
        "every",
        "book",
        "pen",
        "table",
        "chair",
        "door",
        "window",
        "bag",
        "box",
        "key",
        "house",
        "room",
        "bed",
        "paper",
        "computer",
        "phone",
        "big",
        "small",
        "long",
        "short",
        "tall",
        "high",
        "low",
        "new",
        "good",
        "bad",
        "right",
        "wrong",
        "easy",
        "difficult",
        "same",
        "different",
        "beautiful",
        "ugly",
        "pretty",
        "fast",
        "slow",
        "early",
        "late",
        "red",
        "blue",
        "green",
        "yellow",
        "black",
        "white",
        "pink",
        "purple",
        "gray",
        "orange",
        "colour",
        "size",
        "here",
        "there",
        "on",
        "in",
        "under",
        "near",
        "sun",
        "sky",
        "cloud",
        "rain",
        "snow",
        "wind",
        "sunny",
        "rainy",
        "cloudy",
        "windy",
        "weather",
        "many",
        "much",
        "little",
        "few",
        "make",
        "get",
        "use",
        "put",
        "find",
        "read",
        "write",
        "play",
        "walk",
        "run",
        "sit",
        "stand",
        "cook",
        "clean",
        "wash",
        "open",
        "close",
        "turn",
        "learn",
        "study",
        "teach",
        "listen",
        "hear",
        "watch",
        "look",
        "give",
        "show",
        "let",
        "bring",
        "buy",
        "pay",
        "wait",
        "finish",
        "start",
        "stop",
        "try",
        "keep",
        "talk",
        "work",
        "music",
        "song",
        "game",
        "sport",
        "ball",
        "movie",
        "there is",
        "there are",
    ],
    2: [
        "father",
        "mother",
        "brother",
        "sister",
        "son",
        "daughter",
        "family",
        "person",
        "people",
        "man",
        "woman",
        "child",
        "boy",
        "girl",
        "doctor",
        "nurse",
        "live",
        "love",
        "from",
        "speak",
        "young",
        "happy",
        "sad",
        "kind",
        "china",
        "english",
        "have",
        "has",
    ],
    3: [
        "morning",
        "afternoon",
        "evening",
        "night",
        "today",
        "tomorrow",
        "yesterday",
        "now",
        "soon",
        "later",
        "again",
        "then",
        "help",
        "see",
        "call",
        "introduce",
        "welcome",
        "take",
        "care",
        "question",
        "answer",
        "idea",
        "always",
        "never",
        "sometimes",
        "usually",
        "often",
    ],
    4: [
        "one",
        "two",
        "three",
        "four",
        "five",
        "six",
        "seven",
        "eight",
        "nine",
        "ten",
        "eleven",
        "twelve",
        "twenty",
        "thirty",
        "forty",
        "fifty",
        "hundred",
        "thousand",
        "million",
        "first",
        "second",
        "third",
        "time",
        "half",
        "quarter",
        "minute",
        "hour",
        "clock",
        "past",
        "to",
        "day",
        "week",
        "month",
        "year",
        "monday",
        "tuesday",
        "wednesday",
        "thursday",
        "friday",
        "saturday",
        "sunday",
        "january",
        "february",
        "march",
        "april",
        "may",
        "june",
        "july",
        "august",
        "september",
        "october",
        "november",
        "december",
        "spring",
        "summer",
        "autumn",
        "winter",
        "birthday",
        "date",
        "number",
        "car",
        "bus",
        "bike",
        "taxi",
        "train",
        "plane",
        "street",
        "road",
        "city",
        "town",
        "country",
        "school",
        "home",
        "shop",
        "store",
        "restaurant",
        "hospital",
        "park",
        "bank",
        "hotel",
        "office",
        "station",
    ],
    5: [
        "want",
        "need",
        "like",
        "love",
        "can",
        "have",
        "eat",
        "drink",
        "sleep",
        "water",
        "food",
        "breakfast",
        "lunch",
        "dinner",
        "apple",
        "banana",
        "orange",
        "rice",
        "bread",
        "milk",
        "tea",
        "coffee",
        "sugar",
        "salt",
        "egg",
        "meat",
        "fish",
        "hungry",
        "thirsty",
        "tired",
        "hot",
        "cold",
        "warm",
        "head",
        "hand",
        "eye",
        "ear",
        "mouth",
        "nose",
        "hair",
        "arm",
        "leg",
        "foot",
        "body",
        "ill",
        "money",
        "price",
    ],
}

# 5. Build word->meaning mapping (rough Chinese translations)
# Simple dictionary for the most common translations
TRANSLATIONS = {}
# Parse a list of basic translations from the oxford words themselves
# We'll use the word itself as the meaning for now - this needs to be filled in properly

# 6. Assign words to packages
# For each Oxford entry (word, pos, cefr):
# - A1 -> PK①
# - A2 -> PK②-⑦ (match by theme)
# - B1 -> PK⑤-⑩ (match by theme)
# - B2 -> skip (too advanced for foundation)

pos_map = {
    "v.": "verb",
    "n.": "noun",
    "adj.": "adj",
    "adv.": "adv",
    "prep.": "prep",
    "conj.": "conj",
    "pron.": "pron",
    "det.": "det",
    "num.": "num",
    "intj.": "intj",
    "modal": "modal",
    "aux": "aux",
    "phrasal": "phrasal",
}


def norm_pos(p):
    p = p.strip().lower()
    if p in pos_map:
        return pos_map[p]
    if p.startswith("v"):
        return "verb"
    if p.startswith("n"):
        return "noun"
    if p.startswith("adj"):
        return "adj"
    if p.startswith("adv"):
        return "adv"
    if p.startswith("prep"):
        return "prep"
    if p.startswith("conj"):
        return "conj"
    if p.startswith("pron"):
        return "pron"
    if p.startswith("det"):
        return "det"
    if p.startswith("num"):
        return "num"
    if p.startswith("int"):
        return "intj"
    if p.startswith("modal"):
        return "modal"
    if p.startswith("aux"):
        return "aux"
    return p.split("/")[0].strip()


def match_theme(word, themes):
    """Check if word matches any theme keyword"""
    wl = word.lower()
    for theme_words in themes:
        for kw in theme_words:
            if kw in wl or wl in kw:
                return True
    return False


# Process all entries
used_words = set()
pkg_assignments = {p: [] for p in range(1, 11)}

for word, pos_raw, cefr in entries:
    wl = word.lower()
    if wl in used_words:
        continue

    pos = norm_pos(pos_raw)

    # Determine target package
    target_pkg = None
    scene_idx = 0

    if cefr == "A1":
        target_pkg = 1
        # Find best scene
        for si, theme_words in PKG1_SCENE_THEMES.items():
            for tw in theme_words:
                if tw == wl:
                    scene_idx = si
                    break
            else:
                continue
            break
        # Fallback: check theme
        for si, theme_words in PKG1_SCENE_THEMES.items():
            if any(kw in wl or wl in kw for kw in theme_words):
                scene_idx = si
                break

    elif cefr == "A2":
        # Distribute to PK②-⑦ by theme matching
        for pkg_num in [2, 3, 4, 5, 6, 7]:
            if match_theme(word, [PKG_THEMES[pkg_num]]):
                target_pkg = pkg_num
                break
        if target_pkg is None:
            target_pkg = 2  # default fallback

    elif cefr == "B1":
        # Distribute to PK⑤-⑩ by theme
        for pkg_num in [5, 6, 7, 8, 9, 10]:
            if match_theme(word, [PKG_THEMES[pkg_num]]):
                target_pkg = pkg_num
                break
        if target_pkg is None:
            target_pkg = 10  # default fallback

    if target_pkg is None:
        continue

    used_words.add(wl)
    pkg_assignments[target_pkg].append(
        (word, pos, cefr, scene_idx if target_pkg == 1 else 0)
    )

for pkg_num in range(1, 11):
    print(f"PK{pkg_num}: {len(pkg_assignments[pkg_num])} words")

print(f"\nTotal unique words assigned: {len(used_words)}")
remaining = len(all_oxford_words) - len(used_words)
print(f"Unassigned (B2+): {remaining}")
