// Batch generator: Courses 4-6
const fs=require('fs'),p=require('path'),base=p.join(__dirname,'..','data','packages');
const T=(id,name,scenario,focus,vocab,ext,chunks,patterns,dialogue)=>[id,name,scenario,focus,vocab,ext,chunks,patterns,dialogue];
const D=(sp,ln)=>[sp,ln];
function gen(dirName,num,review,grammarNote,scenes){
  const fp=p.join(base,dirName,'学习包的功能介绍.md');
  if(!fs.existsSync(fp)){console.log('SKIP '+dirName);return;}
  let c=fs.readFileSync(fp,'utf8'),idx=c.indexOf('## 逐 Topic 完整教学设计');
  if(idx===-1){console.log('SKIP '+dirName+': no section');return;}
  let o=c.substring(0,idx)+'\n\n## 逐 Topic 完整教学设计\n\n';
  o+=`> 下列内容是生成 CSV、Warmup 与 Ink 的权威 Topic 契约。每个 Topic 均复用：${review}。**注意：以下 20 个 Topic 的对话和句块均独立设计，请勿跨 Topic 复用模板。**\n\n> ${grammarNote}\n\n`;
  let total=0;
  scenes.forEach(([sn,topics],si)=>{topics.forEach((t,ti)=>{total++;
    const[id,name,scenario,focus,vocab,ext,chunks,patterns,dialogue]=t;
    const gi=si*4+ti+1,ol=gi<=8?'2—5':'3—5',wl=gi<=8?'120—250':'180—250',sf=gi<=8?'':'，并回答至少 2 个追问';
    o+=`### Topic ${id} · ${name}\n\n- **教学说明**：在"${scenario}"情境中学习${name}。本Topic聚焦：${focus}。\n- **核心词（Vocabulary）**：${vocab}。\n- **扩展词（Extension）**：${ext}。\n- **核心句块（Chunks）**：`+chunks.map(c=>'`'+c+'`').join('；')+`。\n- **句型（Patterns）**：\`${patterns[0]}\`；\`${patterns[1]}\`。\n- **完成标准**：能在陌生变体中完成 12—16 轮互动，使用至少 3 个核心句块和 1 个主句型，并形成结论、决定或下一步。\n- **口语输出**：围绕"${scenario}"完成 ${ol} 分钟未准备任务；不得照读对话${sf}。\n- **微写作**：写 ${wl} 词，内容必须重新组织，不得抄写口语稿。\n- **反馈与重做**：按任务完成、结构、词汇、语法及发音/拼写反馈；完成第二次重说和重写，7 天后换情境复测。\n- **跨包复习**：${review}；本 Topic 新表达须在本包后续至少两个 Topic 再次主动调用。\n- **具体对话**：\n`;
    dialogue.forEach(([sp,ln],di)=>{o+=`  ${di+1}. ${sp}: ${ln}\n`;});o+='\n';
  });});
  fs.writeFileSync(fp,o,'utf8');console.log('  ✓ '+dirName+' ('+total+' topics)');
}

// ═══ COURSE 4 - 社交关系与沟通边界 ═══
gen('course-4-social-relationships',4,'Course 1 的观点回应与 Foundation 7—8 的礼貌和连接','本包新语法**第二条件句**、**wish/if only** 和 **would 过去习惯**已在各 Topic 的 Chunks 和对话中自然嵌入。',[
['认识与深入交流',[
T('01','自然开启话题','meeting a new neighbour','Starting conversations naturally in social settings','`invitation`,`arrangement`,`support`,`feeling`','`awkward`,`sensitive`',['That reminds me of something similar that happened to me.','I have been meaning to introduce myself—I am Lin, from next door.','It is nice to finally meet you. I have seen you around.','Do you mind if I ask how long you have been living here?'],['That reminds me of ___.','Do you mind if I ask ___?'],[[D('Lin','Hi! I have been meaning to introduce myself. I am Lin, from next door.'),D('Neighbour','Oh, hello! I am Sarah. It is nice to finally meet you.'),D('Lin','It is nice to finally meet you too. Do you mind if I ask how long you have been living here?'),D('Neighbour','About three years now. The neighbourhood has changed a lot.'),D('Lin','That reminds me of something similar—I moved around a lot as a kid, so I know how neighbourhoods evolve.'),D('Neighbour','Well, welcome. Let me know if you ever need anything.'),D('Lin','Thank you. That is really kind of you.']])],
T('02','找共同点','discovering shared interests at a party','Finding common ground to build connection','`invitation`,`interest`,`connection`,`topic`','`genuinely`,`mutual`',['It sounds like we have a lot in common when it comes to music.','I noticed you were reading that book—I just finished it last month.','What drew you to that hobby? I have always been curious about it.','It is rare to meet someone who shares that interest.'],['It sounds like we have a lot in common when it comes to ___.','What drew you to ___?'],[[D('Lin','I noticed you were reading that book. I just finished it last month. What did you think of the ending?'),D('Guest','No way! I have not met anyone else who has read it. I thought the ending was surprising.'),D('Lin','Same here. It sounds like we have a lot in common when it comes to books.'),D('Guest','What other authors do you like?'),D('Lin','I am really into Murakami. What drew you to that author?'),D('Guest','A friend recommended him, and I got hooked.'),D('Lin','It is rare to meet someone who shares that interest. We should swap recommendations sometime.']])],
T('03','追问细节','asking follow-up questions about a story','Showing genuine curiosity through follow-up questions','`curiosity`,`detail`,`follow-up`,`engagement`','`specifically`,`fascinating`',['That is fascinating. Could you tell me more about how that happened?','What was going through your mind at that moment?','You mentioned it was difficult—what made it so challenging?','I would love to hear the rest of that story.'],['Could you tell me more about ___?','What made it so ___?'],[[D('Lin','You mentioned you spent a year teaching abroad. That is fascinating. Could you tell me more about how that happened?'),D('Friend','I applied on a whim, honestly. I did not think I would get accepted.'),D('Lin','What was going through your mind when you found out you got it?'),D('Friend','Terror, mostly. I had never lived outside the country before.'),D('Lin','You mentioned it was difficult at first. What made it so challenging?'),D('Friend','The language barrier. For the first month, I could barely order food.'),D('Lin','I would love to hear the rest of that story sometime. It sounds like quite an adventure.']])],
T('04','结束交流','ending a conversation gracefully','Leaving a conversation without awkwardness','`conversation`,`exit`,`follow-up`,`contact`','`gracefully`,`naturally`',['It was really great talking to you. I hope we can continue this another time.','I should let you go, but let me give you my contact information.','Before I head out, I just wanted to say I really enjoyed this conversation.','Let us definitely stay in touch. I will send you that article I mentioned.'],['It was really great talking to you. ___.','Before I head out, ___.'],[[D('Lin','It was really great talking to you. I hope we can continue this another time.'),D('Friend','Same here. I did not realise we had so much in common.'),D('Lin','I should let you go, but let me give you my contact information first.'),D('Friend','Good idea. Here is my number.'),D('Lin','Before I head out, I just wanted to say I really enjoyed this. Let us definitely stay in touch. I will send you that article I mentioned.'),D('Friend','Looking forward to it. Have a good evening!']])]
]],
['邀请与安排',[
T('05','发出邀请','inviting a colleague to a weekend event','Making invitations that are easy to accept or decline','`invitation`,`plan`,`event`,`availability`','`casually`,`formally`',['I was wondering if you would be interested in joining us this weekend.','No pressure at all, but we are getting a group together for a hike on Saturday.','If you are free, I would love for you to come along.','Feel free to bring a friend if you would like.'],['I was wondering if you would be interested in ___.','If you are free, ___.'],[[D('Lin','Hey, I was wondering if you would be interested in joining us this weekend. A few of us are going hiking on Saturday.'),D('Ben','That sounds nice. Where are you going?'),D('Lin','Blue Mountain trail. No pressure at all—I know weekends can be busy.'),D('Ben','Actually, I have been wanting to go there. What time?'),D('Lin','We are meeting at eight. If you are free, I would love for you to come along. Feel free to bring someone.'),D('Ben','Count me in. I will confirm by Friday.'),D('Lin','Great! I will send you the details.']])],
T('06','协调时间','coordinating schedules for a group dinner','Finding a time that works for multiple people','`schedule`,`availability`,`coordination`,`preference`','`flexible`,`ideally`',['What days work best for everyone next week?','I am free on Tuesday and Thursday. What about the rest of you?','It sounds like Wednesday is the only day that works for most of us.','If we cannot find a time that suits everyone, we could split into two groups.'],['What days work best for ___?','It sounds like ___ is the only day that works.'],[[D('Lin','Okay team, we need to pick a date for the group dinner. What days work best for everyone next week?'),D('Mia','Tuesday or Thursday for me. Wednesday is packed.'),D('Ben','Thursday is best. Tuesday I have a late meeting.'),D('Lin','I am free on Tuesday and Thursday too. It sounds like Thursday is the only day that works for all of us.'),D('Mia','Thursday it is. What time?'),D('Lin','How about seven? That gives everyone time to get there after work.'),D('Ben','Perfect. I will book the table.']])],
T('07','更改计划','changing plans due to an unexpected conflict','Communicating a plan change without disappointing others','`change`,`conflict`,`apology`,`alternative`','`unfortunately`,`instead`',['I am really sorry, but something has come up and I need to reschedule.','I know we had plans, and I feel terrible about changing them.','Could we move our dinner to Friday instead?','I promise I will make it up to you—next time is on me.'],['I am really sorry, but ___.','Could we move ___ to ___ instead?'],[[D('Lin','Mia, I am really sorry, but something has come up and I need to reschedule our dinner tomorrow.'),D('Mia','Oh, is everything okay?'),D('Lin','Yes, just a work deadline that I cannot move. I know we had plans, and I feel terrible.'),D('Mia','Do not worry about it. These things happen.'),D('Lin','Could we move our dinner to Friday instead? I promise I will make it up to you—next time is on me.'),D('Mia','Friday works. And I will hold you to that offer!'),D('Lin','Deal. Thanks for being understanding.']])],
T('08','礼貌拒绝','declining an invitation without damaging the relationship','Saying no while preserving goodwill','`decline`,`appreciation`,`reason`,`alternative`','`regretfully`,`unfortunately`',['Thank you so much for the invitation. I really appreciate you thinking of me.','Unfortunately, I already have plans that evening.','I would have loved to come, but I just cannot make it work this time.','Please keep me in mind for the next one—I would genuinely like to join.'],['Thank you for the invitation. Unfortunately, ___.','Please keep me in mind for ___.'],[[D('Ben','Lin, we are having a game night at my place this Saturday. Would you like to come?'),D('Lin','Thank you so much for the invitation. I really appreciate you thinking of me.'),D('Ben','So, can you make it?'),D('Lin','Unfortunately, I already have plans that evening. My parents are visiting from out of town.'),D('Ben','No worries at all. Family comes first.'),D('Lin','I would have loved to come. Please keep me in mind for the next one—I would genuinely like to join.'),D('Ben','Absolutely. I will let you know about the next one.']])]
]],
['感受与支持',[
T('09','描述情绪','talking about how you have been feeling lately','Using emotional vocabulary accurately','`emotion`,`mood`,`feeling`,`state`','`overwhelmed`,`content`',['To be honest, I have been feeling a bit overwhelmed lately.','It is not one big thing—just a lot of small things piling up.','I do not usually talk about this, but I trust you.','Just saying it out loud actually helps a little.'],['To be honest, I have been feeling ___.','I do not usually talk about this, but ___.'],[[D('Mia','Lin, you have seemed a bit quiet lately. Is everything okay?'),D('Lin','To be honest, I have been feeling a bit overwhelmed lately. It is not one big thing—just a lot of small things piling up.'),D('Mia','I am glad you are telling me. Do you want to talk about it?'),D('Lin','I do not usually talk about this, but I trust you. Work has been intense, and I have not been sleeping well.'),D('Mia','That sounds exhausting. Is there anything I can do?'),D('Lin','Just saying it out loud actually helps a little. Thank you for listening.'),D('Mia','Anytime. You do not have to go through it alone.']])],
T('10','表达理解','showing empathy when a friend is struggling','Validating someone\'s feelings without trying to fix them','`empathy`,`understanding`,`validation`,`presence`','`genuinely`,`deeply`',['That sounds really difficult. I can see why you would feel that way.','You do not have to explain yourself. I am just here to listen.','I have been through something similar, so I have some idea of how you feel.','There is no need to have all the answers right now.'],['That sounds really difficult. ___.','I have been through something similar, so ___.'],[[D('Lin','Ben, you seem down today. Do you want to talk?'),D('Ben','I just found out I did not get the promotion I had been working toward for a year.'),D('Lin','That sounds really difficult. I can see why you would feel that way.'),D('Ben','I feel like I wasted all that time.'),D('Lin','I have been through something similar, so I have some idea of how you feel. It is okay to be disappointed.'),D('Ben','Thanks. I think I just need some time to process it.'),D('Lin','There is no need to have all the answers right now. I am here when you are ready to talk more.']])],
T('11','提供帮助','offering support in a way that respects boundaries','Offering help that is specific and easy to accept','`support`,`offer`,`help`,`boundary`','`practically`,`gently`',['Is there anything specific I can do to help right now?','I do not want to overstep, so please tell me if you would rather handle this alone.','I could help with dinner this week if that would take something off your plate.','No pressure to accept—the offer is there whenever you need it.'],['Is there anything specific I can do to ___?','No pressure to accept—___.'],[[D('Lin','Mia, I know you have been juggling a lot. Is there anything specific I can do to help right now?'),D('Mia','That is really kind. I do not even know where to start.'),D('Lin','I could help with dinner this week if that would take something off your plate. I make a decent stir-fry.'),D('Mia','Actually, that would be amazing. I have not had a home-cooked meal in days.'),D('Lin','I do not want to overstep, so tell me if you would rather handle things alone. No pressure to accept.'),D('Mia','No, I genuinely appreciate it. Thank you, Lin.'),D('Lin','I will drop something off on Wednesday. Hang in there.']])],
T('12','尊重对方选择','accepting when a friend makes a choice you disagree with','Supporting someone even when you would choose differently','`respect`,`choice`,`autonomy`,`support`','`ultimately`,`personally`',['I might not make the same choice, but I respect your decision completely.','What matters most is that this feels right to you.','You have thought this through, and I trust your judgment.','I am still here for you, no matter what you decide.'],['I might not make the same choice, but ___.','What matters most is that ___.'],[[D('Ben','Lin, I have decided to quit my job and go back to school full-time.'),D('Lin','Wow, that is a big decision. How do you feel about it?'),D('Ben','Honestly, terrified but also excited. I have been thinking about it for months.'),D('Lin','I might not make the same choice, but I respect your decision completely. You have thought this through.'),D('Ben','You are not going to try to talk me out of it?'),D('Lin','What matters most is that this feels right to you. I trust your judgment. I am still here for you, no matter what.'),D('Ben','That means a lot. Thank you.']])]
]],
['边界与分歧',[
T('13','表达不舒服','telling someone their comment bothered you','Communicating discomfort without accusation','`discomfort`,`boundary`,`comment`,`feeling`','`unintentionally`,`honestly`',['I wanted to mention something. When you said that earlier, it made me a bit uncomfortable.','I know you probably did not mean it that way, but I wanted to be honest with you.','It is a small thing, but I thought it was better to mention it than to let it build up.','I value our relationship, which is why I am bringing this up.'],['When you said ___, it made me ___.','I value our relationship, which is why ___.'],[[D('Lin','Hey Mia, I wanted to mention something. When you joked about my accent earlier, it made me a bit uncomfortable.'),D('Mia','Oh, I am so sorry. I did not realise it bothered you.'),D('Lin','I know you probably did not mean it that way, but I wanted to be honest. It is a small thing, but I thought it was better to mention it than let it build up.'),D('Mia','I appreciate you telling me. I will be more careful.'),D('Lin','I value our relationship, which is why I am bringing this up. I did not want to just ignore it and feel resentful.'),D('Mia','Thank you for trusting me enough to say something. I really mean that.'),D('Lin','Thank you for hearing me. That is all I needed.']])],
T('14','提出请求','asking someone to change a behaviour','Making a direct but respectful request','`request`,`change`,`need`,`respect`','`directly`,`respectfully`',['I would appreciate it if you could give me a bit more notice next time.','It would help me a lot if you could keep the noise down after ten.','This is not a big deal, but I wanted to ask before it became one.','Is that something you would be open to?'],['I would appreciate it if you could ___.','Is that something you would be open to?'],[[D('Lin','Ben, I would appreciate it if you could give me a bit more notice when you need my help with a project. A few times now, you have asked the night before.'),D('Ben','You are right, I have been doing that. I did not realise it was a pattern.'),D('Lin','It would help me a lot if I had at least two days to plan. This is not a big deal, but I wanted to ask before it became one.'),D('Ben','That is completely fair. I will make sure to give you more lead time from now on.'),D('Lin','Is that something you would be open to? I am not trying to be difficult.'),D('Ben','Absolutely. I am glad you said something.'),D('Lin','Thanks. I appreciate you taking it so well.']])],
T('15','解释边界','explaining a personal boundary clearly','Setting limits while maintaining the relationship','`boundary`,`limit`,`comfort`,`explanation`','`clearly`,`kindly`',['I need to be honest about something: I am not comfortable discussing that topic.','This is just a personal boundary I have, and it is not about you at all.','I hope you understand—it is something I prefer to keep private.','I am happy to talk about other things, just not this particular area.'],['I am not comfortable ___. This is just a personal boundary.','I hope you understand—___.'],[[D('Mia','Lin, why did you not tell me more about your family situation? I feel like you are holding back.'),D('Lin','I need to be honest about something: I am not comfortable discussing my family in detail. This is just a personal boundary I have, and it is not about you at all.'),D('Mia','Oh. I did not mean to push.'),D('Lin','You did not. I hope you understand—it is something I prefer to keep private for now. I am happy to talk about other things, just not this particular area.'),D('Mia','Of course. I respect that completely. Thank you for telling me.'),D('Lin','Thank you for understanding. It actually feels good to have said it.'),D('Mia','I am glad you did. Our friendship is more important than any one topic.']])],
T('16','协商相处方式','negotiating shared living habits with a roommate','Finding a compromise on daily routines','`negotiation`,`routine`,`compromise`,`shared`','`mutually`,`reasonably`',['I have noticed we have different habits around kitchen cleanup. Can we talk about it?','I think we can find a system that works for both of us.','What if we agree on a simple rule: whoever cooks, the other person cleans?','Let us try it for a week and see how it goes.'],['I have noticed we have different habits around ___. Can we talk?','What if we agree on ___?'],[[D('Lin','Hey, I have noticed we have different habits around kitchen cleanup. Can we talk about it?'),D('Roommate','Sure. What is on your mind?'),D('Lin','I tend to clean as I go, and I have noticed dishes sometimes sit overnight. I am not blaming anyone—I just want to find a system that works for both of us.'),D('Roommate','That is fair. I get busy and forget. What do you suggest?'),D('Lin','What if we agree on a simple rule: whoever cooks, the other person cleans up by the end of the night?'),D('Roommate','That sounds reasonable. Let us try it for a week and see how it goes.'),D('Lin','Great. I will check in with you next Sunday.']])]
]],
['误解与修复',[
T('17','发现误解','realising you misinterpreted a friend\'s action','Acknowledging a misunderstanding without defensiveness','`misunderstanding`,`assumption`,`realisation`,`clarification`','`apparently`,`actually`',['I think I may have misunderstood what you meant earlier.','I had assumed something different, and I want to check if I was wrong.','When you did not reply to my message, I thought you were upset with me. Was that not the case?','Thank you for clarifying. I am glad I asked instead of assuming.'],['I think I may have misunderstood ___.','When you ___, I thought ___. Was that the case?'],[[D('Lin','Mia, I think I may have misunderstood something. When you did not reply to my message for two days, I thought you were upset with me.'),D('Mia','Oh no, not at all! My phone broke, and I just got a replacement today.'),D('Lin','I had assumed something completely different. I am embarrassed now.'),D('Mia','Do not be. I should have found another way to let you know.'),D('Lin','Thank you for clarifying. I am glad I asked instead of assuming. I spent two days worrying for nothing.'),D('Mia','Next time, just call me. I am never upset without telling you why.'),D('Lin','I will remember that. Lesson learned.']])],
T('18','道歉与承担','apologising sincerely for hurting someone','Taking full responsibility without making excuses','`apology`,`responsibility`,`regret`,`amends`','`sincerely`,`genuinely`',['I owe you an apology. What I said was thoughtless, and it hurt you.','There is no excuse for it. I should have known better.','I am not going to make excuses. I was wrong, and I am sorry.','What can I do to make this right?'],['I owe you an apology. ___.','I am not going to make excuses. ___.'],[[D('Lin','Ben, I owe you an apology. What I said in the meeting yesterday was thoughtless, and I can see it hurt you.'),D('Ben','It did sting. I felt undermined in front of everyone.'),D('Lin','There is no excuse for it. I should have raised my concern with you privately. I am not going to make excuses—I was wrong, and I am sorry.'),D('Ben','I appreciate you saying that. It means more than you know.'),D('Lin','What can I do to make this right? I want to rebuild the trust.'),D('Ben','Honestly, just checking in like this helps a lot. Let us move forward.'),D('Lin','Thank you. I will not let it happen again.']])],
T('19','解释而不推卸','explaining your actions without deflecting blame','Giving context without using it as an excuse','`explanation`,`context`,`accountability`,`ownership`','`admittedly`,`understandably`',['I want to explain what was going through my mind, but not as an excuse.','The reason I reacted that way is because I was under a lot of pressure—but that does not make it okay.','I take full responsibility for how I handled it, regardless of the circumstances.','I am telling you this so you understand, not so you let me off the hook.'],['I want to explain ___, but not as an excuse.','I take full responsibility for ___, regardless of ___.'],[[D('Lin','I want to explain what was going through my mind when I snapped at you, but not as an excuse.'),D('Emma','Go ahead. I want to understand.'),D('Lin','I had just received some bad news about my family, and I was not in a good place. But that does not make it okay to take it out on you.'),D('Emma','I did not know you were dealing with that.'),D('Lin','I take full responsibility for how I handled it, regardless of the circumstances. I am telling you this so you understand, not so you let me off the hook.'),D('Emma','I appreciate the honesty. And I am sorry about your family.'),D('Lin','Thank you. Next time, I will just tell you what is going on instead of bottling it up.']])],
T('20','恢复关系','rebuilding a friendship after a conflict','Taking steps to repair and move forward','`repair`,`rebuild`,`trust`,`moving forward`','`gradually`,`intentionally`',['I really value our friendship, and I do not want this to create distance between us.','What do you need from me to feel okay about moving forward?','I am committed to doing better, and I hope we can rebuild from here.','Let us not pretend it did not happen, but let us also not let it define us.'],['I really value our friendship, and ___.','Let us not pretend ___, but let us also not ___.'],[[D('Lin','Emma, I really value our friendship, and I do not want what happened to create distance between us.'),D('Emma','I feel the same way. It has been awkward, and I hate that.'),D('Lin','What do you need from me to feel okay about moving forward? I am committed to doing better.'),D('Emma','Honestly, just consistency. Show me that things will be different, not just tell me.'),D('Lin','That is fair. Let us not pretend it did not happen, but let us also not let it define us. How about we grab coffee this weekend and just talk?'),D('Emma','I would like that. It has been too long.'),D('Lin','Great. Saturday at ten? I will be there.']])]
]]
]);

console.log('\n✓ Course 4 complete (20 topics)');
console.log('⏳ Courses 5-6 still need processing in the companion script.');
