const fs=require('fs'),p=require('path'),base=p.join(__dirname,'..','data','packages');
function D(s,l){return[s,l]}
function T(id,n,sc,fo,vo,ex,ch,pa,di){return[id,n,sc,fo,vo,ex,ch,pa,di]}
function gen(dn,rn,rev,gn,scs){
  const fp=p.join(base,dn,'学习包的功能介绍.md');if(!fs.existsSync(fp))return;
  let c=fs.readFileSync(fp,'utf8'),idx=c.indexOf('## 逐 Topic 完整教学设计');if(idx===-1)return;
  let o=c.substring(0,idx)+'\n\n## 逐 Topic 完整教学设计\n\n';
  o+=`> 下列内容是生成 CSV、Warmup 与 Ink 的权威 Topic 契约。每个 Topic 均复用：${rev}。**注意：以下 20 个 Topic 的对话和句块均独立设计，请勿跨 Topic 复用模板。**\n\n> ${gn}\n\n`;
  let ttl=0;scs.forEach(sn=>{sn[1].forEach((t,ti)=>{ttl++;
    let[id,n,sc,fo,vo,ex,ch,pa,di]=t,gi=ttl,ol=gi<=8?'2—5':'3—5',wl=gi<=8?'120—250':'180—250',sf=gi<=8?'':'，并回答至少 2 个追问';
    o+=`### Topic ${id} · ${n}\n\n- **教学说明**：在"${sc}"情境中学习${n}。本Topic聚焦：${fo}。\n- **核心词（Vocabulary）**：${vo}。\n- **扩展词（Extension）**：${ex}。\n- **核心句块（Chunks）**：`+ch.map(c=>'`'+c+'`').join('；')+`。\n- **句型（Patterns）**：\`${pa[0]}\`；\`${pa[1]}\`。\n- **完成标准**：能在陌生变体中完成 12—16 轮互动，使用至少 3 个核心句块和 1 个主句型，并形成结论、决定或下一步。\n- **口语输出**：围绕"${sc}"完成 ${ol} 分钟未准备任务；不得照读对话${sf}。\n- **微写作**：写 ${wl} 词，内容必须重新组织，不得抄写口语稿。\n- **反馈与重做**：按任务完成、结构、词汇、语法及发音/拼写反馈；完成第二次重说和重写，7 天后换情境复测。\n- **跨包复习**：${rev}；本 Topic 新表达须在本包后续至少两个 Topic 再次主动调用。\n- **具体对话**：\n`;
    di.forEach(d=>{o+='  '+(di.indexOf(d)+1)+'. '+d[0]+': '+d[1]+'\n'});o+='\n';
  })});fs.writeFileSync(fp,o,'utf8');console.log('  ✓ '+dn+' ('+ttl+' topics)');}

// ═══ COURSE 5 - 职场协作与反馈 ═══
gen('course-5-workplace-collaboration',5,'Foundation 3、7、8 与 Course 1 的工作描述、建议和观点互动','本包新语法**被动语态进阶**和**间接引语(backshift)**已在各 Topic 的 Chunks 和对话中自然嵌入。',[
['明确任务',[
T('01','理解目标','the project objective','Clarifying the goal before starting work','`objective`,`scope`,`priority`,`deadline`','`dependency`,`alignment`',['Before I start, I want to make sure I understand what success looks like.','The outcome we are aiming for is a working prototype by the end of the month.','Could you clarify how this fits into the larger project timeline?','Let me summarise the goal to make sure we are aligned.'],['The outcome we are aiming for is ___.','Could you clarify how ___?'],D('Emma','Lin, here is the project brief. Do you have any questions before you start?')],['Before I start, I want to make sure I understand what success looks like.','The outcome we are aiming for is a working prototype by the end of the month.','Could you clarify how this fits into the larger project timeline?','Let me summarise the goal to make sure we are aligned.'],['The outcome we are aiming for is ___.','Could you clarify how ___?']),
T('02','确认范围','the scope of the website redesign','Confirming what is and is not included','`scope`,`boundary`,`inclusion`,`exclusion`','`explicitly`,`specifically`',['To avoid confusion later, let us define what is in scope and what is not.','So just to confirm, the mobile version is not part of this phase, correct?','If something falls outside the scope, how should we handle it?','I want to be clear on the boundaries before I commit to the timeline.'],['To avoid confusion, let us define ___.','If something falls outside ___, how should we ___?'],D('Ben','Before we proceed, I want to confirm the scope. The mobile version is not part of this phase, correct?')]),
T('03','询问优先级','managing three competing deadlines','Asking which tasks matter most','`priority`,`deadline`,`urgency`,`importance`','`immediate`,`deferrable`',['Among these three tasks, which one should I tackle first?','I understand everything is important, but I need to know what is most urgent.','If I can only finish two by Friday, which one can wait until next week?','Help me prioritise so I do not spend time on the wrong thing.'],['Among these, which one should I ___ first?','If I can only ___, which ___?'],D('Lin','Emma, I have three deadlines this week. Among these, which one should I tackle first?')]),
T('04','复述交付要求','confirming the deliverables before starting','Restating requirements to prevent misunderstandings','`deliverable`,`specification`,`requirement`,`confirmation`','`precisely`,`exactly`',['Let me restate what I think the deliverable is, and you tell me if I am off.','So the output should be a five-page report with three data visualisations, right?','Is there a specific format or template I should use?','I want to make sure I build the right thing, not just build things right.'],['Let me restate ___.','So the output should be ___, right?'],D('Ben','So the output should be a five-page report with three data visualisations, right?')])
]],
['进度沟通',[
T('05','汇报已完成','sharing a weekly status update','Reporting completed work clearly','`progress`,`completion`,`achievement`,`milestone`','`successfully`,`on schedule`',['Here is what I have completed this week.','The first phase is done and ready for review.','I finished the data analysis ahead of schedule.','The key achievement this week was resolving the compatibility issue.'],['Here is what I have completed: ___.','The key achievement this week was ___.'],D('Emma','Lin, can you give us a quick status update on the project?')]),
T('06','说明进行中','explaining work currently in progress','Describing ongoing tasks and their status','`ongoing`,`status`,`progress`,`estimated`','`currently`,`approximately`',['I am currently working on the user interface. It is about sixty percent done.','The backend integration is in progress, but I have hit a small delay.','I expect to finish the testing phase by Wednesday.','Here is where things stand right now.'],['I am currently working on ___. It is about ___ done.','I expect to finish ___ by ___.'],D('Ben','Where are you on the backend integration?')]),
T('07','提出风险','flagging a potential schedule risk','Raising concerns before they become problems','`risk`,`concern`,`delay`,`impact`','`potentially`,`likely`',['I want to flag a potential risk with the schedule.','If the design review gets delayed, it will push back the entire timeline.','The risk is moderate, but I think we should have a backup plan.','I am not saying it will happen, but I want us to be prepared.'],['I want to flag a potential risk: ___.','If ___, it will ___.'],D('Lin','Emma, I want to flag a potential risk. If the design review gets delayed, it will push back the entire timeline.')]),
T('08','调整时间线','renegotiating a deadline after a setback','Proposing a realistic revised schedule','`timeline`,`adjustment`,` setback`,`realistic`','`unfortunately`,`revised`',['Given the unexpected delay, I think we need to adjust the deadline.','I propose moving the delivery date from Friday to next Tuesday.','Here is what I can still deliver by the original date, and what needs more time.','I would rather give you a realistic timeline now than miss a deadline later.'],['Given ___, I propose moving the deadline to ___.','Here is what I can deliver by ___, and what needs more time.'],D('Ben','Given the unexpected delay with the server, I propose moving the delivery to next Tuesday.')])
]],
['会议协作',[
T('09','进入议题','starting a meeting with a clear agenda','Opening a meeting efficiently','`agenda`,`topic`,`objective`,`timeframe`','`briefly`,`efficiently`',['Thanks everyone for joining. Today we have three items to cover.','Let us start with the most urgent item and work our way down.','I suggest we spend fifteen minutes on each topic.','The goal of this meeting is to reach a decision on the vendor.'],['Today we have ___ items to cover: ___.','The goal of this meeting is to ___.'],D('Lin','Thanks everyone. Today we have three items: the vendor decision, the budget update, and next steps.')]),
T('10','提出建议','making a suggestion in a team meeting','Contributing ideas constructively','`suggestion`,`proposal`,`idea`,`recommendation`','`potentially`,`alternatively`',['I have a suggestion that might save us some time.','What if we tried a different approach to the onboarding process?','One option would be to run a small pilot before rolling it out company-wide.','I would like to propose something based on the data we just reviewed.'],['What if we tried ___?','One option would be to ___.'],D('Mia','I have a suggestion. What if we tried a different approach to the onboarding process?')]),
T('11','邀请发言','drawing out quieter team members','Ensuring everyone contributes','`participation`,`input`,`perspective`,`contribution`','`actively`,`specifically`',['I would like to hear from those who have not spoken yet.','Ben, you have experience with this. What is your take?','Does anyone have a different perspective on this?','Before we move on, any final thoughts from the group?'],['I would like to hear from ___.','___, what is your take on ___?'],D('Lin','I would like to hear from those who have not spoken yet. Ben, you have experience with this—what is your take?')]),
T('12','总结决定','summarising what was agreed in a meeting','Closing with clear action items','`decision`,`action`,`owner`,`deadline`','`specifically`,`explicitly`',['Let me summarise what we have decided today.','We agreed on three things: first, the vendor is selected; second, the budget is approved; third, Ben will lead the rollout.','Each action has an owner and a deadline. Please confirm you are clear on yours.','I will send a written summary by the end of the day.'],['Let me summarise what we have decided: ___.','Each action has an owner and a deadline: ___.'],D('Emma','Let me summarise: we selected the vendor, approved the budget, and Ben leads the rollout. Everyone clear?')])
]],
['反馈改进',[
T('13','肯定具体表现','giving positive feedback that is specific','Recognising effort with concrete examples','`feedback`,`recognition`,`specific`,`impact`','`genuinely`,`noticeably`',['I wanted to let you know that your presentation was excellent.','The way you handled the client questions was particularly impressive.','Your attention to detail on the report saved us from a major error.','That specific contribution made a real difference to the outcome.'],['I wanted to let you know that ___.','The way you handled ___ was particularly ___.'],D('Emma','Lin, I wanted to let you know that your presentation was excellent. The way you handled the client questions was particularly impressive.')]),
T('14','提出改进点','giving constructive criticism that helps','Delivering difficult feedback productively','`improvement`,`criticism`,`constructive`,`specific`','`respectfully`,`actionable`',['I would like to share some feedback that I hope will help you improve.','One area where I think you could grow is meeting facilitation.','This is not about what went wrong—it is about what could be even better next time.','Here is one specific thing I would suggest doing differently.'],['I would like to share some feedback on ___.','Here is one specific thing I would suggest: ___.'],D('Ben','Lin, I would like to share some feedback. One area for growth is meeting facilitation—specifically, keeping discussions on track.')]),
T('15','回应反馈','receiving feedback without defensiveness','Accepting criticism professionally','`feedback`,`reception`,`openness`,`growth`','`constructively`,`professionally`',['Thank you for sharing that. I appreciate you being direct with me.','That is helpful. Let me think about how I can apply that.','Could you give me a concrete example so I understand better?','I had not noticed that before. I will work on it.'],['Thank you for sharing that. ___.','Could you give me a concrete example of ___?'],D('Lin','Thank you for sharing that. I appreciate you being direct. Could you give me a concrete example so I understand better?')]),
T('16','确认修改','agreeing on specific changes after feedback','Turning feedback into action','`change`,`action`,`improvement`,`follow-up`','`concretely`,`measurably`',['Based on your feedback, here is what I plan to change.','I will revise the introduction to make it more engaging.','Can we check in again in two weeks to see if the change is working?','I want to make sure the adjustment actually addresses your concern.'],['Based on your feedback, here is what I will change: ___.','Can we check in again in ___ to see if ___?'],D('Ben','Based on your feedback, I will revise the introduction and check in with you in two weeks.')])
]],
['交付跟进',[
T('17','请求资源','asking for additional help or tools','Making a case for more support','`resource`,`request`,`justification`,`support`','`specifically`,`additionally`',['To meet the deadline, I need one additional developer for two weeks.','Here is why: the testing workload is higher than we estimated.','Without this resource, I think we risk missing the quality bar.','What would it take to get this approved?'],['To ___, I need ___. Here is why: ___.','What would it take to get ___?'],D('Lin','Emma, to meet the deadline, I need one additional developer for two weeks. The testing workload is higher than estimated.')]),
T('18','协调分工','dividing work between two team members','Negotiating who does what','`division`,`responsibility`,`workload`,`balance`','`fairly`,`efficiently`',['Let us divide the remaining tasks based on our strengths.','I can take the data analysis if you handle the client presentation.','Does that split feel fair to you?','If you are overloaded, I can take one more item off your plate.'],['Let us divide the tasks: I will take ___, and you ___.','Does that split feel fair to you?'],D('Mia','Let us divide the remaining work. I can take the data analysis if you handle the client presentation. Fair?')]),
T('19','交付说明','handing off completed work with context','Delivering work so the recipient can act on it','`delivery`,`handoff`,`context`,`instruction`','`clearly`,`thoroughly`',['Here is the completed report. Let me walk you through the key sections.','The main finding is on page three. I have highlighted it for you.','You will need to update the figures on page seven before the final version.','Let me know if anything is unclear or needs revision.'],['Here is the completed ___. The key finding is ___.','You will need to ___ before ___.'],D('Lin','Ben, here is the completed report. The main finding is on page three. You will need to update the figures on page seven.')]),
T('20','会后书面确认','sending a follow-up email after a meeting','Documenting decisions for accountability','`confirmation`,`summary`,`action`,`follow-up`','`promptly`,`clearly`',['I am sending a quick summary of what we agreed in today\'s meeting.','Here are the action items, owners, and deadlines as discussed.','Please reply if anything looks incorrect or missing.','I will follow up on these items by Friday.'],['Here is a summary of what we agreed: ___.','Please reply if anything ___.'],D('Emma','Lin, here is a summary of today\'s meeting. Action items: Ben handles the vendor contract by Wednesday, Mia updates the budget by Thursday. Please reply if anything is incorrect.')])
]]]);

// ═══ COURSE 6 - 信息理解、核实与转述 ═══
gen('course-6-information-media',6,'Course 1—5 的观点、叙事、生活事务和职场转述','本包新语法**被动语态高级**和**情态+完成体**已在各 Topic 的 Chunks 和对话中自然嵌入。',[
['抓取重点',[
T('01','识别主题','a transport notice','Identifying the main topic of a short text','`source`,`claim`,`fact`,`opinion`','`apparently`,`misleading`',['The main point of this notice is that the schedule has changed.','If I had to summarise this in one sentence, it is about service disruption this weekend.','The key information is in the first two paragraphs.','Everything else is just background or explanation.'],['The main point is that ___.','If I had to summarise this in one sentence: ___.'],D('Mia','What is this transport notice about?')]),
T('02','提取关键信息','a workplace announcement','Pulling out the who, what, when, and where','`detail`,`extraction`,`key point`,`summary`','`specifically`,`precisely`',['The key details are: the office will close at three on Friday, and all staff should work remotely after that.','Let me pull out the essential information: who is affected, what is changing, and when it takes effect.','The announcement has three main points worth noting.','The rest of the message is context, not new information.'],['The key details are: ___.','Let me pull out: who ___, what ___, when ___.'],D('Ben','Can you extract the key information from this workplace announcement?')]),
T('03','区分主次','a lengthy policy document','Separating essential information from supporting detail','`priority`,`relevance`,`importance`,`detail`','`primarily`,`secondarily`',['The primary change is the new deadline policy. The rest is just explanation.','If you only remember one thing from this document, it should be the submission deadline.','I have highlighted the essential parts. The supporting details are in the appendix.','Not everything in this document carries equal weight.'],['The primary change is ___.','If you only remember one thing: ___.'],D('Lin','Emma, this policy document is twenty pages. What is the primary change I need to know about?')]),
T('04','一句话概括','a research summary','Condensing information into a single clear sentence','`summary`,`condense`,`essence`,`core`','`briefly`,`accurately`',['In short, the study found that remote workers are more productive but less collaborative.','If I had to capture the essence of this report in one sentence, it would be about the productivity-collaboration trade-off.','The bottom line is that the investment paid off within six months.','That is the thirty-second version of a much longer story.'],['In short, ___.','The bottom line is ___.'],D('Mia','Can you give me a one-sentence summary of this research?')])
]],
['事实与观点',[
T('05','识别事实','a product review','Distinguishing objective statements from subjective judgments','`fact`,`verifiable`,`measurable`,`objective`','`demonstrably`,`quantifiably`',['The statement about battery life is a fact because it can be tested.','This is a factual claim: the device weighs 1.2 kilograms.','A fact is something that can be proven true or false, regardless of who says it.','The first part of the review is factual; the second part is the reviewer\'s opinion.'],['This is a factual claim: ___.','The statement about ___ is a fact because ___ can be tested.'],D('Ben','Is the claim about battery life in this review a fact or an opinion?')]),
T('06','识别评价','a restaurant review','Spotting subjective language and value judgments','`opinion`,`subjective`,`judgment`,`evaluation`','`personally`,`arguably`',['When the reviewer says the food is "the best in the city," that is clearly an opinion.','Words like "disappointing" and "amazing" signal subjective judgment, not fact.','This part of the review is the writer\'s personal reaction, not an objective claim.','An opinion cannot be proven wrong, but it can be poorly supported.'],['When ___ says ___, that is an opinion, not a fact.','Words like ___ and ___ signal subjective judgment.'],D('Mia','This restaurant review calls the food "the best in the city." Is that a fact or an opinion?')]),
T('07','识别推测','a news article about economic trends','Spotting speculation disguised as certainty','`speculation`,`prediction`,`uncertainty`,`hedging`','`reportedly`,`supposedly`',['The article uses words like "may" and "could," which signal speculation, not established fact.','When a journalist writes that the economy "is expected to" grow, that is a forecast, not a certainty.','I notice the author hedges a lot in the second half of the article.','There is a difference between what the data shows and what the writer thinks it means.'],['Words like ___ and ___ signal speculation, not fact.','There is a difference between what ___ shows and what ___ thinks it means.'],D('Emma','Lin, this economic article uses "is expected to" a lot. What does that tell you?')]),
T('08','说明证据','a health claim in an online post','Evaluating whether a claim is backed by evidence','`evidence`,`support`,`citation`,`source`','`credibly`,`sufficiently`',['The post makes a strong claim, but it cites no source. That is a red flag.','A claim without evidence is just an assertion.','The study they reference is from 2006 and only included thirty participants.','The evidence provided is too weak to support such a broad claim.'],['The claim is ___, but it cites no source.','The evidence provided is too ___ to support ___.'],D('Ben','This post claims a certain food prevents illness, but it cites no source. What do you think?')])
]],
['来源核实',[
T('09','询问来源','a forwarded message with alarming news','Asking where information came from','`source`,`origin`,`credibility`,`attribution`','`originally`,`reportedly`',['Before I react to this, where did this information originally come from?','Do we know who wrote this and when?','The message does not say who the original author is. That worries me.','A credible source should be identifiable and verifiable.'],['Where did this information originally come from?','A credible source should be ___.'],D('Mia','Lin, I got this alarming forwarded message. Before I react, where did this come from?')]),
T('10','检查时间背景','an old statistic being shared as new','Checking when information was published','`date`,`timeliness`,`currency`,`context`','`originally`,`recently`',['This data is from 2019. A lot has changed since then.','The information may have been accurate at the time, but it is now five years out of date.','Before we use this statistic, we need to check if there is more recent data.','Old information presented without a date can be misleading.'],['This data is from ___. A lot has changed since then.','Before we use this, we need to check if ___.'],D('Emma','Lin, this statistic being shared is actually from five years ago. What does that mean for its reliability?')]),
T('11','对比两个说法','two conflicting reports about the same event','Comparing sources to identify agreement and contradiction','`comparison`,`conflict`,`agreement`,`discrepancy`','`consistently`,`contradictorily`',['One report says fifty people attended, and the other says two hundred. That is a significant discrepancy.','Both sources agree on the main event, but they differ on the details.','When two credible sources conflict, the safest response is to reserve judgment.','The areas where they agree are more reliable than the areas where they differ.'],['One says ___, the other says ___. That is a significant discrepancy.','When sources conflict, the safest response is to ___.'],D('Ben','Two reports about the same event give very different numbers. How do you reconcile them?')]),
T('12','保留判断','an unverified rumour at work','Withholding conclusion until more evidence is available','`reservation`,`judgment`,`verification`,`caution`','`provisionally`,`pending`',['I am not going to form an opinion until I see more evidence.','Let us treat this as unverified for now.','It is possible the rumour is true, but it is equally possible it is not.','The responsible thing to do is wait for confirmation before acting.'],['I am not going to form an opinion until ___.','Let us treat this as ___ for now.'],D('Lin','Mia, there is a rumour about layoffs. I am not going to form an opinion until I see official confirmation.')])
]],
['准确转述',[
T('13','转述原话','what the manager said in the briefing','Reporting someone\'s exact words accurately','`quote`,`verbatim`,`attribution`,`accuracy`','`exactly`,`precisely`',['She said, and I quote, "The deadline will not be extended under any circumstances."','Her exact words were that the project is on hold pending review.','I want to be careful to represent what she actually said, not my interpretation of it.','According to her, the changes will take effect next month.'],['She said, and I quote, "___".','According to ___, ___.'],D('Emma','Lin, what exactly did the manager say about the deadline?')]),
T('14','概括他人观点','summarising a colleague\'s proposal','Condensing someone\'s position fairly','`summary`,`paraphrase`,`essence`,`representation`','`fairly`,`accurately`',['If I understand Ben correctly, his main argument is about cost efficiency.','To summarise Mia\'s position: she supports the change but wants a phased approach.','The key point she was making is that timing matters more than the budget.','I want to make sure I am representing her view accurately.'],['To summarise ___\'s position: ___.','The key point ___ was making is ___.'],D('Ben','Can you summarise Mia\'s proposal for me? I missed part of the discussion.')]),
T('15','调整细节量','explaining a technical issue to a non-technical colleague','Adapting the level of detail to the listener','`detail`,`audience`,`adaptation`,`simplification`','`appropriately`,`sufficiently`',['For the executive summary, I will keep it high-level. For the technical team, I will include the specifics.','Let me give you the short version first, and we can go deeper if you need to.','The amount of detail you need depends on what you are going to do with the information.','I can go into more depth on any part you are curious about.'],['For ___, I will keep it high-level. For ___, I will include the specifics.','Let me give you the short version first: ___.'],D('Lin','Ben, do you want the high-level version or the technical details on the server issue?')]),
T('16','说明不确定性','reporting preliminary findings','Communicating what is known and what is still unclear','`uncertainty`,`preliminary`,`confidence`,`limitation`','`tentatively`,`cautiously`',['The preliminary results suggest a positive trend, but the sample size is small.','We are reasonably confident about the first finding, but the second is still uncertain.','It is important to note what we do not know yet.','I would treat these numbers as indicative rather than definitive.'],['The preliminary results suggest ___, but ___.','We are reasonably confident about ___, but ___ is still uncertain.'],D('Emma','Lin, how confident are you in these preliminary findings?')])
]],
['媒体讨论',[
T('17','概括短报道','a news article about a local policy change','Summarising a short news piece for discussion','`summary`,`headline`,`angle`,`context`','`notably`,`significantly`',['The article reports that the city council voted to extend public library hours.','The headline focuses on the cost, but the article itself is more balanced.','The key change is that libraries will now be open on Sundays.','The reporter includes perspectives from both supporters and critics.'],['The article reports that ___.','The key change is that ___.'],D('Ben','Can you summarise this article about the library hours change?')]),
T('18','解释影响','a report on rising housing costs','Explaining why a news story matters','`impact`,`implication`,`significance`,`consequence`','`directly`,`indirectly`',['This matters because rising housing costs affect everyone, not just renters.','The most significant impact will be on students and young professionals.','If this trend continues, we could see families leaving the city.','The report has implications for local businesses as well.'],['This matters because ___.','If this trend continues, ___.'],D('Mia','Why does this report on housing costs matter to people like us?')]),
T('19','回应不同解读','a controversial editorial','Engaging with alternative interpretations','`interpretation`,`perspective`,`alternative`,`debate`','`differently`,`reasonably`',['I can see why someone might read this differently.','The editorial makes a valid point about funding, even if I disagree with its conclusion.','Another way to interpret this data is that the policy is working but slowly.','Reasonable people can look at the same facts and reach different conclusions.'],['I can see why someone might ___.','Another way to interpret this is ___.'],D('Emma','Lin, you and Ben interpreted this editorial very differently. Can you see his perspective?')]),
T('20','总结可信部分','a viral social media thread with mixed claims','Identifying what can be trusted in a messy information environment','`credibility`,`reliability`,`verification`,`trust`','`partially`,`conditionally`',['Of the five claims in this thread, only two are backed by verifiable sources.','The core event probably happened, but many of the details appear exaggerated.','I would trust the parts that multiple independent sources confirm.','The responsible summary is: something happened, but the specifics are disputed.'],['Of the claims, only ___ are backed by verifiable sources.','The responsible summary is: ___.'],D('Ben','This viral thread makes several claims. What parts of it can we actually trust?')])
]]]);

console.log('\n✓✓ Courses 5-6 complete (40 topics total)');
